export type ToolDisplayTier = "hidden" | "process" | "action" | "interactive" | "result";

const TOOL_TIER: Record<string, ToolDisplayTier> = {
  think_tool: "hidden",
  extended_thinking: "hidden",
  record_result: "hidden",
  record_failure: "hidden",
  report_task_result: "hidden",
  get_libraries: "hidden",
  get_learning_stats: "hidden",
  extract_entities: "hidden",

  read_file: "process",
  batch_read_files: "process",
  list_directory: "process",
  grep_search: "process",
  file_search: "process",
  search_knowledge: "process",
  query_kg: "process",
  knowledge_graph: "process",
  ontology: "process",
  ontology_import: "process",
  web_search: "process",
  web_fetch: "process",
  analyze_document: "process",
  analyze_image: "process",
  learn_from_doc: "process",
  list_skills: "process",
  match_skills: "process",
  get_skill_info: "process",
  run_skill_script: "process",

  write_file: "action",
  generate_ppt: "action",
  generate_image: "action",
  generate_video: "action",
  edit_file: "action",
  delete_file: "action",
  python_run: "action",
  execute_python_code: "action",
  shell_run: "action",
  execute: "action",
  create_chart: "action",

  ask_user: "interactive",
  plan_next_moves: "interactive",
  write_todos: "interactive",
  task: "interactive",
  critic_review: "result",

  web_crawl_batch: "process",
  content_extract: "process",
  template_render: "action",
  manage_memory: "hidden",
  search_memory: "process",
  search_learning_experience: "process",
  get_similar_paths: "process",
  generate_pdf: "action",
  generate_word: "action",
  verify_output: "hidden",
  verify_knowledge_entry: "hidden",
  verify_ontology_entity: "hidden",
  enter_plan_mode: "interactive",
  exit_plan_mode: "interactive",
};

export function getToolTier(toolName: string): ToolDisplayTier {
  return TOOL_TIER[toolName] ?? "process";
}
