"""
文档生成工具 - Phase 6 Task 3

利用 code_run 的库集成能力生成各种文档格式
供 Document Agent 直接使用

═══════════════════════════════════════════════════════════════════════════════
"""

from typing import Dict, Any, List, Optional
from langchain_core.tools import tool
from langchain_core.messages import AIMessage
import asyncio
import os
from pathlib import Path

import logging

from backend.tools.base.paths import get_workspace_root

logger = logging.getLogger(__name__)


def _resolve_output_path(output_path: str) -> str:
    """相对路径解析到工作区 outputs 目录，保证生成文件落入 output。"""
    p = Path(output_path)
    if not p.is_absolute():
        base = get_workspace_root() / "outputs"
        p = (base / output_path).resolve()
        p.parent.mkdir(parents=True, exist_ok=True)
    return str(p)


# ═══════════════════════════════════════════════════════════════════════════════
# 📋 文档生成核心函数
# ═══════════════════════════════════════════════════════════════════════════════

def _resolve_slide_image_path(item: Dict[str, Any], output_dir: str) -> Optional[str]:
    """解析单页幻灯片的图片：支持 image_path（本地）或 image_url（下载到 output_dir 后返回路径）。"""
    image_path = (item.get("image_path") or item.get("image_url") or "").strip()
    if not image_path:
        return None
    if image_path.startswith(("http://", "https://")):
        try:
            import urllib.request
            from urllib.parse import urlparse
            name = Path(urlparse(image_path).path).name or "image"
            if not name.lower().endswith((".png", ".jpg", ".jpeg", ".gif", ".webp")):
                name += ".png"
            local_path = str(Path(output_dir) / f"slide_img_{abs(hash(image_path)) % 10**8}_{name}")
            urllib.request.urlretrieve(image_path, local_path)
            return local_path
        except Exception as e:
            logger.warning("PPT 幻灯片图片下载失败 %s: %s", image_path[:80], e)
            return None
    p = Path(image_path)
    if not p.is_absolute():
        p = (get_workspace_root() / p).resolve()
    return str(p) if p.exists() else None


async def _generate_ppt_internal(
    title: str,
    content: List[Dict[str, Any]],
    output_path: str = "output.pptx",
) -> Dict[str, Any]:
    """
    内部实现：生成 PowerPoint 文档
    
    Args:
        title: 演示文稿标题
        content: 幻灯片内容列表
                 格式: [{"heading": "...", "text": "...", "image_path": "可选", "image_url": "可选"}, ...]
        output_path: 输出文件路径
    
    Returns:
        生成结果
    """
    output_path = _resolve_output_path(output_path)
    output_dir = str(Path(output_path).parent)
    try:
        # ✅ 检查依赖是否安装
        try:
            from pptx import Presentation
            from pptx.util import Inches, Pt
        except ImportError as import_err:
            logger.warning(f"⚠️ python-pptx 未安装: {import_err}")
            return {
                "status": "error",
                "error": f"python-pptx 模块未安装。请运行: pip install python-pptx",
                "message": f"PPT 生成失败: python-pptx 模块未安装。请运行: pip install python-pptx"
            }
        
        # 创建演示文稿
        prs = Presentation()
        prs.slide_width = Inches(10)
        prs.slide_height = Inches(7.5)
        
        # 添加标题幻灯片
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title_shape = slide.shapes.title
        subtitle = slide.placeholders[1]
        title_shape.text = title
        subtitle.text = "Generated by Document Agent"
        
        # 添加内容幻灯片
        bullet_slide_layout = prs.slide_layouts[1]
        for item in content:
            slide = prs.slides.add_slide(bullet_slide_layout)
            title_shape = slide.shapes.title
            body_shape = slide.placeholders[1]
            title_shape.text = item.get("heading", "")
            text_frame = body_shape.text_frame
            text_frame.clear()
            p = text_frame.paragraphs[0]
            p.text = item.get("text", "")
            # 可选：本页配图（image_path 本地路径 或 image_url 下载后插入）
            raw_url = (item.get("image_url") or "").strip()
            if raw_url.startswith(("http://", "https://")):
                img_path = await asyncio.to_thread(_resolve_slide_image_path, item, output_dir)
            else:
                img_path = _resolve_slide_image_path(item, output_dir)
            if img_path:
                try:
                    # 固定宽度下按宽高比计算高度，避免长图被压扁；无 Pillow 时使用固定尺寸
                    pic_width_em = 3.5
                    pic_height_em = 2.6
                    try:
                        from PIL import Image
                        with Image.open(img_path) as im:
                            w, h = im.size
                            if w and h:
                                ratio = h / w
                                pic_height_em = min(pic_width_em * ratio, 5.0)
                    except Exception:
                        pass
                    slide.shapes.add_picture(
                        img_path,
                        Inches(6.2),
                        Inches(1.8),
                        width=Inches(pic_width_em),
                        height=Inches(pic_height_em),
                    )
                except Exception as img_err:
                    logger.warning("PPT 插入图片失败 %s: %s", img_path[:80], img_err)
        
        # 保存
        prs.save(output_path)
        
        return {
            "status": "success",
            "file": output_path,
            "slides": len(content) + 1,
            "message": f"PPT 文档已生成: {output_path}"
        }
    
    except Exception as e:
        logger.error(f"PPT 生成失败: {e}")
        return {
            "status": "error",
            "error": str(e),
            "message": f"PPT 生成失败: {e}"
        }


async def _generate_pdf_internal(
    title: str,
    content: str,
    output_path: str = "output.pdf",
) -> Dict[str, Any]:
    """
    内部实现：生成 PDF 文档
    
    Args:
        title: 文档标题
        content: 文档内容（纯文本或 HTML）
        output_path: 输出文件路径
    
    Returns:
        生成结果
    """
    output_path = _resolve_output_path(output_path)
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.units import inch
        
        # 创建 PDF 文档
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        story = []
        
        # 样式
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=18,
            textColor='#1f4788',
            spaceAfter=30,
            alignment=1  # 居中
        )
        
        # 添加标题
        story.append(Paragraph(title, title_style))
        story.append(Spacer(1, 0.3 * inch))
        
        # 添加内容
        body_style = styles['BodyText']
        for line in content.split('\n'):
            if line.strip():
                story.append(Paragraph(line, body_style))
                story.append(Spacer(1, 0.2 * inch))
        
        # 生成 PDF
        doc.build(story)
        
        return {
            "status": "success",
            "file": output_path,
            "size": os.path.getsize(output_path),
            "message": f"PDF 文档已生成: {output_path}"
        }
    
    except Exception as e:
        logger.error(f"PDF 生成失败: {e}")
        return {
            "status": "error",
            "error": str(e),
            "message": f"PDF 生成失败: {e}"
        }


async def _generate_word_internal(
    title: str,
    content: List[Dict[str, str]],
    output_path: str = "output.docx",
) -> Dict[str, Any]:
    """
    内部实现：生成 Word 文档
    
    Args:
        title: 文档标题
        content: 段落列表
                 格式: [{"heading": "...", "text": "..."}, ...]
        output_path: 输出文件路径
    
    Returns:
        生成结果
    """
    output_path = _resolve_output_path(output_path)
    try:
        # ✅ 检查依赖是否安装
        try:
            from docx import Document
            from docx.shared import Pt, RGBColor
            from docx.enum.text import WD_ALIGN_PARAGRAPH
        except ImportError as import_err:
            logger.warning(f"⚠️ python-docx 未安装: {import_err}")
            return {
                "status": "error",
                "error": f"python-docx 模块未安装。请运行: pip install python-docx",
                "message": f"Word 生成失败: python-docx 模块未安装。请运行: pip install python-docx"
            }
        
        # 创建 Word 文档
        doc = Document()
        
        # 添加标题
        title_para = doc.add_paragraph(title)
        title_para.style = 'Heading 1'
        title_para_format = title_para.paragraph_format
        title_para_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # 添加内容
        for item in content:
            # 小标题
            if item.get("heading"):
                heading = doc.add_paragraph(item["heading"])
                heading.style = 'Heading 2'
            
            # 文本
            if item.get("text"):
                text = doc.add_paragraph(item["text"])
                text.style = 'Normal'
        
        # 保存
        doc.save(output_path)
        
        return {
            "status": "success",
            "file": output_path,
            "paragraphs": len(content) + 1,
            "message": f"Word 文档已生成: {output_path}"
        }
    
    except ImportError as import_err:
        logger.error(f"Word 生成失败 - 依赖缺失: {import_err}")
        return {
            "status": "error",
            "error": f"python-docx 模块未安装: {import_err}",
            "message": f"Word 生成失败: python-docx 模块未安装。请运行: pip install python-docx"
        }
    except Exception as e:
        logger.error(f"Word 生成失败: {e}")
        return {
            "status": "error",
            "error": str(e),
            "message": f"Word 生成失败: {e}"
        }


# ═══════════════════════════════════════════════════════════════════════════════
# @tool 导出给 LLM
# ═══════════════════════════════════════════════════════════════════════════════

@tool
async def generate_ppt(
    title: str,
    slides: List[Dict[str, Any]],
    output_file: str = "proposal.pptx",
) -> AIMessage:
    """Generate PowerPoint presentation (.pptx).

    Use when:
    - 需要结构化演示文稿交付（汇报、提案、方案说明）。
    - 已有按页组织的标题与正文数据；可选每页配图。

    Avoid when:
    - 内容仍是草稿，尚未完成结构化分段。
    - 只需要纯文本导出（优先 generate_pdf/generate_word）。

    Strategy:
    - 先在上游把内容拆成 slides 列表，再调用本工具一次生成。
    - 每页可含 "heading", "text", 以及可选的 "image_path"（本地路径）或 "image_url"（图片 URL），用于插入配图。

    Args:
        title: Presentation title
        slides: List of slide dicts with "heading", "text", and optionally "image_path" or "image_url"
        output_file: Output path (default: proposal.pptx)
    """
    result = await _generate_ppt_internal(title, slides, output_file)
    
    if result["status"] == "success":
        # 返回包含两个 UI 组件的消息：
        # 1. file_generated - 在聊天区域显示
        # 2. editor_action - 自动触发编辑器操作（衍生动作）
        return AIMessage(
            content=f"✅ PPT 已生成: {result['file']} ({result['slides']} 张幻灯片)",
            additional_kwargs={
                "ui": [
                    {
                        "type": "file_generated",
                        "target": "chat",  # 在聊天区域显示
                        "file_path": result["file"],
                        "file_type": "pptx",
                        "metadata": {
                            "slides": result["slides"],
                            "title": title,
                        }
                    },
                    {
                        "type": "editor_action",
                        "action": "open",
                        "target": "editor",  # 自动触发编辑器操作
                        "file_path": result["file"],
                        "auto_trigger": True,  # 标识这是衍生动作
                    }
                ]
            }
        )
    else:
        return AIMessage(
            content=f"❌ PPT 生成失败: {result.get('error', '未知错误')}"
        )


@tool
async def generate_pdf(
    title: str,
    content: str,
    output_file: str = "proposal.pdf",
) -> AIMessage:
    """Generate PDF document (.pdf).

    Use when:
    - 需要不可编辑、格式稳定的最终交付版本。
    - 内容以段落文本为主，可按换行组织。

    Avoid when:
    - 需要后续频繁编辑（优先 generate_word）。
    - 需要复杂版式（表格/图片排版）但未预处理内容。

    Strategy:
    - 先清洗内容并控制段落长度，避免 PDF 中出现密集大段文本。
    - 生成后立即校验文件大小与页面可读性。

    Args:
        title: Document title
        content: Text content (use \\n for line breaks)
        output_file: Output path (default: proposal.pdf)
    """
    result = await _generate_pdf_internal(title, content, output_file)
    
    if result["status"] == "success":
        return AIMessage(
            content=f"✅ PDF 已生成: {result['file']} ({result['size']} bytes)",
            additional_kwargs={
                "ui": [
                    {
                        "type": "file_generated",
                        "target": "chat",
                        "file_path": result["file"],
                        "file_type": "pdf",
                        "metadata": {
                            "size": result["size"],
                            "title": title,
                        }
                    },
                    {
                        "type": "editor_action",
                        "action": "open",
                        "target": "editor",
                        "file_path": result["file"],
                        "auto_trigger": True,
                    }
                ]
            }
        )
    else:
        return AIMessage(
            content=f"❌ PDF 生成失败: {result.get('error', '未知错误')}"
        )


@tool
async def generate_word(
    title: str,
    sections: List[Dict[str, str]],
    output_file: str = "proposal.docx",
) -> AIMessage:
    """Generate Word document (.docx).

    Use when:
    - 需要可编辑的正式文档（方案、报告、说明书）。
    - 内容已按 sections 列表拆分。

    Avoid when:
    - 只需要阅读分发且不允许编辑（优先 generate_pdf）。
    - sections 数据结构不完整（先做数据清洗）。

    Strategy:
    - 每个 section 保持“heading + text”最小结构，便于自动样式化。
    - 生成后由用户在编辑器进行轻量修订再导出终稿。

    Args:
        title: Document title
        sections: List of section dicts with "heading" and "text"
        output_file: Output path (default: proposal.docx)
    """
    result = await _generate_word_internal(title, sections, output_file)
    
    if result["status"] == "success":
        return AIMessage(
            content=f"✅ Word 已生成: {result['file']} ({result['paragraphs']} 个段落)",
            additional_kwargs={
                "ui": [
                    {
                        "type": "file_generated",
                        "target": "chat",
                        "file_path": result["file"],
                        "file_type": "docx",
                        "metadata": {
                            "paragraphs": result["paragraphs"],
                            "title": title,
                        }
                    },
                    {
                        "type": "editor_action",
                        "action": "open",
                        "target": "editor",
                        "file_path": result["file"],
                        "auto_trigger": True,
                    }
                ]
            }
        )
    else:
        return AIMessage(
            content=f"❌ Word 生成失败: {result.get('error', '未知错误')}"
        )


# ═══════════════════════════════════════════════════════════════════════════════
# 工具集合
# ═══════════════════════════════════════════════════════════════════════════════

DOCUMENT_GENERATION_TOOLS = [
    generate_ppt,
    generate_pdf,
    generate_word,
]

__all__ = [
    "generate_ppt",
    "generate_pdf",
    "generate_word",
    "DOCUMENT_GENERATION_TOOLS",
]

